### ISSUE TITLE
No se renderiza el logo de omegaUp

### ISSUE THREAD

**Issue by heduenas** [omegaup/blog#35]
Solo se muestra "Blog". Se tiene que mostrar "Blog omegaUp" con el logo.
<img width="873" alt="Screenshot 2024-11-23 at 12 42 06 PM" src="https://github.com/user-attachments/assets/b486b5c5-fcb5-4ecf-9caa-c160d83963e0">

**Comment by IsmaelSantanaR** [comment]
Listo en el PR #37 
![image](https://github.com/user-attachments/assets/b8fab28d-2b1f-48ad-9819-4c9714f39002)
